### ISSUE TITLE
Strange blue frame on screen

### ISSUE THREAD

**Issue by dacaes** [sigtrapgames/VrTunnellingPro-Unity#3]
![image](https://user-images.githubusercontent.com/9904952/52500473-647a9500-2bde-11e9-9e17-bc0192a87abe.png)

- It only happens on build.
- It scales bouncy when I don't move but move my head and when I move (I have tunnelling effect set up to show only when player moves with the joystick), it is always behind tunnelling effect (I use vignetting default mask), it seems to be scaled the same size as the tunnelling effect.
- I am using Oculus Rift, forward rendering and Single Pass.

Have you ever have this kind of issue?

Thank you.

**Comment by dacaes** [comment]
Thanks to the user Drezus on Unity's forums [VR Tunnelling Pro thread](https://forum.unity.com/threads/free-vr-tunnelling-pro-plug-and-play-vr-comfort.517537/), I've found that Iris Z Rejection is what causes that.

From VR Tunnelling Pro [Manual](http://www.sigtrapgames.com/VrTunnellingPro/html/bkg.html) I've found that:

"Various modes allow the Iris Z Rejection setting, an optimization that saves pixel fillrate and overdraw. Before the scene is drawn, this writes to the z-buffer where the vignette is opaque. This stops pixels being written only to be obscured by the effect."

So, disabling Iris Z Rejection, the blue frame is gone, but I can't benefit from the performance improvement Iris Z Rejection grants.

**Comment by SixWays** [comment]
Switching to the dev branch should fix this issue. It's a weird bug where unity doesn't export mesh vertex colours correctly on standalone builds - I've changed to a different method on the dev branch.

**Comment by dacaes** [comment]
Thank you! @SixWays

**Comment by sigtrapgames** [comment]
Dev has now been merged into master so this should no longer be a problem - however, please let me know if it is! -Luke
