### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Sev73n** [sigtrapgames/VrTunnellingPro-Unity#4]
![Snipaste_2019-12-02_02-48-12](https://user-images.githubusercontent.com/16495885/69917873-3a1c0000-14ae-11ea-8005-799d2407246e.png)
I am using Unity 2019 and with oculus sdk

**Comment by ROBYER1** [comment]
What specific engine version are you using? I have tested in 2019.2, 2019.3 and 2020.1 without any issue here. Make sure you reimport the package correctly and that everything is selected to import from the package.

**Comment by Sev73n** [comment]
it is my mistake，I use a script directly on ovrcamerarig，In fact, it should be placed in the ovrcamerarig---centercamera，The problem has been resolved Thank you for your reply!
