### ISSUE TITLE
Single-Pass Instanced on Desktop only works for the left eye

### ISSUE THREAD

**Issue by ROBYER1** [sigtrapgames/VrTunnellingPro-Unity#5]
Currently using the XR Subsystems Management Package with Oculus XR Loader for Unity 2019.3 and 2020, on mobile platforms it works perfectly fine with Multi-View (Single Pass) but on desktop with Single-Pass Instanced (the only option other than Multi Pass), it only renders for the left eye.

I have a reproducible project if need be but the asset store pack basically exhibits the same issue.

![single pass issues](https://user-images.githubusercontent.com/10745594/70141933-000a5400-1690-11ea-8cf1-9163bc982fbb.PNG)

**Comment by sigtrapgames** [comment]
To clarify - does this happen with the version from GitHub? I've not tried with the new XR system yet but this sounds like an issue which was fixed on here a little bit ago, and I've not yet updated the store version.

**Comment by ROBYER1** [comment]
This was fixed by your team at some point on the github version, I forgot to close this!
